import { defineStore } from 'pinia';
import { DataStore } from '@aws-amplify/datastore';
import { Building } from '../models'; // Generated by Amplify's codegen

export const useBuildingsStore = defineStore('buildings', {
  state: () => ({
    buildings: [],
  }),
  actions: {
    async fetchBuildings() {
      try {
        this.buildings = await DataStore.query(Building);
      } catch (error) {
        console.error('Failed to fetch buildings:', error);
      }
    },
    async createBuilding(buildingData) {
      try {
        const newBuilding = await DataStore.save(new Building(buildingData));
        this.buildings.push(newBuilding);
      } catch (error) {
        console.error('Failed to create building:', error);
      }
    },
  },
});
